# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

languages = [
    {name: 'Afrikaans', code: 'af', flag: '🇿🇦'},
    {name: 'Albanian', code: 'sq', flag: '🇦🇱'},
    {name: 'Arabic', code: 'ar', flag: '🇸🇦'},
    {name: 'Azerbaijani', code: 'az', flag: '🇦🇿'},
    {name: 'Basque', code: 'eu', flag: ''},
    {name: 'Irish', code: 'ga', flag: '🇨🇮'},
    {name: 'Italian', code: 'it', flag: '🇮🇹'},
    {name: 'Japanese', code: 'ja', flag: '🇯🇵'},
    {name: 'Kannada', code: 'kn', flag: ''},
    {name: 'Korean', code: 'ko', flag: '🇰🇷'},
    {name: 'Bengali', code: 'bn', flag: '🇧🇩'},
    {name: 'Latin', code: 'la', flag: ''},
    {name: 'Belarusian', code: 'be', flag: '🇧🇾'},
    {name: 'Latvian', code: 'lv', flag: '🇱🇻'},
    {name: 'Bulgarian', code: 'bg', flag: '🇧🇬'},
    {name: 'Lithuanian', code: 'lt', flag: '🇱🇹'},
    {name: 'Catalan', code: 'ca', flag: ''},
    {name: 'Macedonian', code: 'mk', flag: '🇲🇰'},
    {name: 'Chinese Simplified', code: 'zh-CN', flag: '🇨🇳'},
    {name: 'Malay', code: 'ms', flag: '🇲🇾'},
    {name: 'Chinese Traditional', code: 'zh-TW', flag: '🇨🇳'},
    {name: 'Maltese', code: 'mt', flag: '🇲🇹'},
    {name: 'Croatian', code: 'hr', flag: '🇭🇷'},
    {name: 'Norwegian', code: 'no', flag: '🇳🇴'},
    {name: 'Czech', code: 'cs', flag: '🇨🇿'},
    {name: 'Persian', code: 'fa', flag: '🇮🇷'},
    {name: 'Danish', code: 'da', flag: '🇩🇰'},
    {name: 'Polish', code: 'pl', flag: '🇵🇱'},
    {name: 'Dutch', code: 'nl', flag: '🇳🇱'},
    {name: 'Portuguese', code: 'pt', flag: '🇵🇹'},
    {name: 'English', code: 'en', flag: '🇬🇧'},
    {name: 'Romanian', code: 'ro', flag: '🇷🇴'},
    {name: 'Esperanto', code: 'eo', flag: ''},
    {name: 'Russian', code: 'ru', flag: '🇷🇺'},
    {name: 'Estonian', code: 'et', flag: '🇪🇪'},
    {name: 'Serbian', code: 'sr', flag: '🇷🇸'},
    {name: 'Filipino', code: 'tl', flag: '🇸🇽'},
    {name: 'Slovak', code: 'sk', flag: '🇸🇰'},
    {name: 'Finnish', code: 'fi', flag: '🇫🇮'},
    {name: 'Slovenian', code: 'sl', flag: ''},
    {name: 'French', code: 'fr', flag: '🇫🇷'},
    {name: 'Spanish', code: 'es', flag: '🇪🇸'},
    {name: 'Galician', code: 'gl', flag: ''},
    {name: 'Swahili', code: 'sw', flag: '🇹🇿'}, 
    {name: 'Georgian', code: 'ka', flag: '🇬🇪'},
    {name: 'Swedish', code: 'sv', flag: '🇸🇪'},
    {name: 'German', code: 'de', flag: '🇩🇪'},
    {name: 'Tamil', code: 'ta', flag: '🇱🇰'},
    {name: 'Greek', code: 'el', flag: '🇬🇷'},
    {name: 'Telugu', code: 'te', flag: '🇮🇳'},   
    {name: 'Gujarati', code: 'gu', flag: '🇮🇳'},
    {name: 'Thai', code: 'th', flag: '🇹🇭'},    
    {name: 'Haitian Creole', code: 'ht', flag: '🇭🇹'},
    {name: 'Turkish', code: 'tr', flag: '🇹🇷'},    
    {name: 'Hebrew', code: 'iw', flag: '🇮🇱'},
    {name: 'Ukrainian', code: 'uk', flag: '🇺🇦'},   
    {name: 'Hindi', code: 'hi', flag: '🇮🇳'},
    {name: 'Urdu', code: 'ur', flag: '🇵🇰'},   
    {name: 'Hungarian', code: 'hu', flag: '🇭🇺'},
    {name: 'Vietnamese', code: 'vi', flag: '🇻🇳'},   
    {name: 'Icelandic', code: 'is', flag: '🇮🇸'},
    {name: 'Welsh', code: 'cy', flag: ''},   
    {name: 'Indonesian', code: 'id', flag: '🇮🇩'},
    {name: 'Yiddish', code: 'yi', flag: ''}
]

languages.each { |l| Language.create(l) }
